# vim: set fileencoding=utf-8
from bs4 import BeautifulSoup
import re
import datetime
import pgdb
import logging
import string
import json

import main
import mc_util
import mc_db
import themortgagemeter_utils

institution_code = 'NTNWD'
term = str(25 * 12)

def process_page(url,ltv,eligibility,mortgage_type,logger):
#  "Rates": [
#    {
#      "Apr": 3.7,
#      "AssetUrl": "58305",
#      "Availability": "All",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 3,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 1.94,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 420.93,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "2 Year Fixed Rate (First Time Buyer)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 24,
#      "Withdrawn": false
	resp = themortgagemeter_utils.get_page(False,'',url,logger,tostring=True)
	json_obj = json.loads(resp)
	mortgage_list = json_obj['Rates']
	if mortgage_list == 'none':
		logger.info('URL returned nothing: ' + url)
		return
	for mortgage in mortgage_list:
		rate_percent = str(mortgage['InitialRate'])
		svr_percent = str(mortgage['RevertRate1'])
		apr_percent = str(mortgage['Apr'])
		initial_period = str(mortgage['Term'])
		booking_fee = str(int(mortgage['BookingFee'] + mortgage['SpecialProductFee'] + mortgage['FeesPayable']))
		ltv_percent = str(mortgage['MaxLoanToValue'])
		mc_util.handle_mortgage_insert(institution_code,mortgage_type,rate_percent,svr_percent,apr_percent,ltv_percent,initial_period,booking_fee,term,'http://www.nationwide.co.uk',eligibility,logger)


	

def nationwide_main(static,forcedelete,logger):
	#<option value="ftb">First time buyer</option>
	#<option value="nc-mh">New customer - moving home</option>
	#<option value="nc-r">New customer - remortgaging</option>
	#<option value="ec-mh">Existing customer - moving</option>
	#<option value="ec-bm">Existing customer - borrowing more</option> <-- doesn't seem to return mortgages when last tried
	#<option value="ec-de">Existing customer - deal ended</option>
	#<option value="ec-sf">Existing customer - switch and fix mid-deal</option>
	mortgage_amount = "150000"
	for buyer_type in ("ec-de","ec-bm","ftb", "nc-mh", "nc-r", "ec-mh", "ec-sf"):
		for ltv in ("60","70","75","80","85","90","95","100"):
			for product_type in ('fixed','tracker'):
			# NOW:
			#http://www.nationwide.co.uk/services/toolservice.svc/GetFullMortgageRates?buyerType=ftb&loanToValueTier=60&productType=all&mortgageTerm=25&mortgageAmount=100000&submit=true
				url = "http://www.nationwide.co.uk/services/toolservice.svc/GetFullMortgageRates?buyerType=" + buyer_type + "&loanToValueTier=" + ltv + "&productType=" + product_type + "&mortgageTerm=25&mortgageAmount=" + mortgage_amount
				if product_type == 'fixed':
					mortgage_type = 'F'
				elif product_type == 'tracker':
					mortgage_type = 'T'
				logger.debug("Doing: " + ltv + " " + mortgage_amount + " " + buyer_type + " " + product_type)
				if buyer_type == 'ftb':
					eligibility = "NFTB"
				elif buyer_type == 'nc-mh':
					eligibility = "NMH"
				elif buyer_type == 'nc-r':
					eligibility = "NRM"
				elif buyer_type == 'ec-mh':
					eligibility = "EMH"
				elif buyer_type == 'ec-bm':
					eligibility = "EBM"
				elif buyer_type == 'ec-de':
					eligibility = "EDE"
				elif buyer_type == 'ec-sf':
					eligibility = "EED"
				process_page(url,ltv,eligibility,mortgage_type,logger)
	mc_db.update_current(institution_code,main.today,forcedelete,logger)
#{
#  "Rates": [
#    {
#      "Apr": 3.7,
#      "AssetUrl": "58305",
#      "Availability": "All",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 3,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 1.94,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 420.93,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "2 Year Fixed Rate (First Time Buyer)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 24,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.7,
#      "AssetUrl": "58644",
#      "Availability": "All",
#      "BaseRateDifferential": 1.44,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 2.5,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 1.94,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 420.93,
#      "MortgageType": 1,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "2 Year Tracker Rate (First time buyer only)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 24,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.8,
#      "AssetUrl": "58735",
#      "Availability": "All non LL",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "New Borrower non LL ",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 3,
#      "FeesPayable": 99,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.34,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 440.6,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "2 Year Fixed Rate (new borrowers) ",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 24,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.8,
#      "AssetUrl": "59105",
#      "Availability": "All non LL",
#      "BaseRateDifferential": 1.84,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "New Borrower non LL ",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 2.5,
#      "FeesPayable": 99,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.34,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 440.6,
#      "MortgageType": 1,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "2 Year Tracker Rate (new borrowers) ",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 24,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "58684",
#      "Availability": "All",
#      "BaseRateDifferential": 1.59,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 3,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.09,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 428.24,
#      "MortgageType": 1,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "3 Year Tracker Rate (First time buyer only)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 36,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "58372",
#      "Availability": "All",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 4,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.29,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 438.11,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "3 Year Fixed Rate (First Time Buyer)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 36,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "59157",
#      "Availability": "All non LL",
#      "BaseRateDifferential": 1.89,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "New Borrower non LL ",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 3,
#      "FeesPayable": 99,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.39,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 443.09,
#      "MortgageType": 1,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "3 Year Tracker Rate (new borrowers)",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 36,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "58821",
#      "Availability": "All non LL",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "New Borrower non LL ",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 4,
#      "FeesPayable": 99,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.59,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 453.16,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "3 Year Fixed Rate (new borrowers) ",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 36,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "58465",
#      "Availability": "NBS Only (All)",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "FTB Flexclusive",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 4,
#      "FeesPayable": 499,
#      "HasFreeLegals": true,
#      "HasFreeValuations": true,
#      "InitialRate": 2.59,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 453.16,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "4 Year Fixed Rate (First Time Buyer - NBS Solicitor) ",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": true,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 48,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.6,
#      "AssetUrl": "58932",
#      "Availability": "NBS Only (All)",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "NewBorrow NBS",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 4,
#      "FeesPayable": 99,
#      "HasFreeLegals": true,
#      "HasFreeValuations": true,
#      "InitialRate": 2.89,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 468.5,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "4 Year Fixed Rate (new borrowers - NBS Solicitor) ",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": true,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 48,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.3,
#      "AssetUrl": "59201",
#      "Availability": "NBS Only (All)",
#      "BaseRateDifferential": 2.09,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "NewBorrow NBS",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 0,
#      "FeesPayable": 99,
#      "HasFreeLegals": true,
#      "HasFreeValuations": true,
#      "InitialRate": 2.59,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 453.16,
#      "MortgageType": 1,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "5 Year Tracker Rate (new borrowers) ",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": true,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 60,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.7,
#      "AssetUrl": "58573",
#      "Availability": "All",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "First Time Buyer",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 5,
#      "FeesPayable": 499,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 2.99,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 473.69,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "5 Year Fixed Rate (First Time Buyer)",
#      "ProductFee": 400,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 60,
#      "Withdrawn": false
#    },
#    {
#      "Apr": 3.7,
#      "AssetUrl": "59032",
#      "Availability": "All non LL",
#      "BaseRateDifferential": 0,
#      "BookingFee": 99,
#      "CashBackAmount": 0,
#      "Changed": "Changed",
#      "Eligibility": "New Borrower non LL ",
#      "EligibilityFeatures": null,
#      "ErcPercentage": 5,
#      "FeesPayable": 99,
#      "HasFreeLegals": false,
#      "HasFreeValuations": false,
#      "InitialRate": 3.19,
#      "MaxLoanAmount": 1000000,
#      "MaxLoanToValue": 60,
#      "MinLoanAmount": 25000,
#      "MinLoanToValue": 0,
#      "MonthlyRepayment": 484.15,
#      "MortgageType": 0,
#      "OverpaymentAmountAllowed": 0,
#      "ProductDescription": "5 Year Fixed Rate (new borrowers)",
#      "ProductFee": 0,
#      "RequiresExistingBorrower": false,
#      "RequiresFirstTimeBuyer": true,
#      "RequiresFlexAccount": false,
#      "RequiresFurtherAdvance": false,
#      "RequiresHomeMover": true,
#      "RequiresOwnSolicitor": false,
#      "RequiresRemortgage": false,
#      "ReservationFeeScale": "",
#      "RevertRate1": 3.99,
#      "SpecialProductFee": 900,
#      "Term": 60,
#      "Withdrawn": false
#    }
#  ],
#  "RequestDate": "2013-12-29 10:05:45Z",
#  "ResultCount": 13
#}
